version: 1
disable_existing_loggers: true



formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%d-%H:%M:%S"
    error:
        format: "%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
        datefmt: "%Y-%m-%d-%H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /opt/logs/check_mysql_slave/check_mysql_slave.info.log
        maxBytes: 10485760 # 10MB
        backupCount: 7
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /opt/logs/check_mysql_slave/check_mysql_slave.errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 7
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /opt/logs/check_mysql_slave/check_mysql_slave.debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 7
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /opt/logs/check_mysql_slave/check_mysql_slave.critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 7
        encoding: utf8
    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /opt/logs/check_mysql_slave/check_mysql_slave.warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 7
        encoding: utf8

root:
    level: NOTSET
    handlers: [console,info_file_handler, error_file_handler]
    propogate: yes

loggers:
    <module>:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes

    <module.x>:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: yes
